---
- name: Gather HPE Synergy OS Support information
  hosts: localhost

  tasks:
    - name: Gather facts about Synergy OS Support
      uri:
        url: https://hpe-synergy-software-api.herokuapp.com/synergyOsSupport
      register: response
      delegate_to: localhost

    # - debug: var=response.json[4]

    - name: Getting supported Synergy Service Packs for VMware ESXi
      set_fact:
        vmwareEsxi: "{{ response.json[4].vmwareEsxi }}"

    #- debug: var=vmwareEsxi

    - set_fact:
        supported_osVersions_for_480Gen10: "{{ vmwareEsxi |
          selectattr('model', 'equalto', 'SY 480 Gen10') |
          map(attribute='osVersions') |
          list }}"
        supported_osVersions_for_480Gen10plus: "{{ vmwareEsxi |
          selectattr('model', 'equalto', 'SY 480 Gen10 Plus') |
          map(attribute='osVersions') |
          list }}"

    #- debug: var=supported_osVersions_for_480

    - name: Getting supported Synergy Service Packs for VMware ESXi 7.0 Update 3 with HPE Synergy 480 Gen10
      set_fact:
        supported_ssp_for_480Gen10_with_ESXi70U3:
          "{{ supported_osVersions_for_480Gen10[0] |
          selectattr('osVersion', 'equalto', 'VMware ESXi 7.0 Update 3') |
          list }}"

    - debug: var=supported_ssp_for_480Gen10_with_ESXi70U3

    - name: Getting supported Synergy Service Packs for VMware ESXi 6.7 Update 3 from May 2021 with HPE Synergy 480 Gen10
      set_fact:
        supported_ssp_for_480Gen10_with_ESXi70U2:
          "{{ supported_osVersions_for_480Gen10[0] |
          selectattr('osVersion', 'equalto', 'VMware ESXi 6.7 Update 3') |
          selectattr('releaseDate', 'equalto', '2021-05-01') |
          list }}"

    - debug: var=supported_ssp_for_480Gen10_with_ESXi70U2

    - name: Getting supported Synergy Service Packs for VMware ESXi 7.0 Update 3 with SHPE Synergy 480 Gen10+
      set_fact:
        supported_ssp_for_480Gen10plus_with_ESXi70U3:
          "{{ supported_osVersions_for_480Gen10plus[0] |
          selectattr('osVersion', 'equalto', 'VMware ESXi 7.0 Update 3') |
          list }}"

    - debug: var=supported_ssp_for_480Gen10plus_with_ESXi70U3
