---
- name: Gather HPE Synergy OS Support information
  hosts: localhost
  
  tasks:
    - name: Gather facts about Synergy OS Support  
      uri:        
        url: https://hpe-synergy-software-api.herokuapp.com/synergyOsSupport
      register: response
      delegate_to: localhost

    # - debug: var=response.json[0]

    - name: Getting supported Synergy Service Packs for VMware ESXi
      set_fact:
        vmwareEsxi: "{{ response.json[0].vmwareEsxi }}"

    #- debug: var=vmwareEsxi

    - name: Getting supported OS versions with SY 480 Gen10
      set_fact:
        supported_osVersions_for_480: "{{ vmwareEsxi | 
          selectattr('model', 'equalto', 'SY 480 Gen10') | 
          map(attribute='osVersions') |
          list }}"

    #- debug: var=supported_osVersions_for_480

    - name: Getting supported Synergy Service Packs for VMware 6.7 SP3 with SY 480 Gen10
      set_fact:
        supported_ssp_for_480_with_ESXi70U3: "{{ supported_osVersions_for_480[0] | 
          selectattr('osVersion', 'equalto', 'VMware ESXi 7.0 Update 3') | 
          map(attribute='supportedSsp') |
          list }}"

    - debug: var=supported_ssp_for_480_with_ESXi70U3          

    - name: Getting supported Synergy Service Packs for VMware 6.7 SP2 from May 2021 with SY 480 Gen10
      set_fact:
        supported_ssp_for_480_with_ESXi70U2: "{{ supported_osVersions_for_480[0] | 
          selectattr('osVersion', 'equalto', 'VMware ESXi 7.0 Update 2') | 
          selectattr('releaseDate', 'equalto', '2021-05-01') |
          map(attribute='supportedSsp') |
          list }}"

    - debug: var=supported_ssp_for_480_with_ESXi70U2          
